name: 2025-baker-ellipsoids
channels:
  - conda-forge
dependencies:
  - python
  # IPython and Jupyter
  - ipython
  - jupyter
  - jupyterlab
  # Linters and testing
  - ruff
  - pytest
  # Scientific stack
  - numpy==2.2
  - scipy
  - harmonica
  - choclo
  - verde
  - matplotlib
  - numba==0.61.2
